# 触发器
name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    # 设置jdk环境为1.8
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      # 打包release
      - name: Build with Gradle
        run: |
          ./gradlew clean
          ./gradlew assembleRelease

      #step：上传apk 到action，在右上角查看
      # 官方文档 https://help.github.com/cn/actions/automating-your-workflow-with-github-actions/persisting-workflow-data-using-artifacts#uploading-build-and-test-artifacts
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: app
          path: app/build/outputs/apk/release/app-release.apk


      - name: Release APK
        # You may pin to the exact commit or the version.
        # uses: ShowMeThe/github_action_release@c03188563c3286ccd20cf0d2b1413a134e3cabc9
        uses: ShowMeThe/github_action_release@v0.01
        with:
          # Github secret token to allow automated publishing of APK to release.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      # 获取apk版本号
#      - name: APK Version
#        id: apk_version
#        run: |
#          versionCode=`grep "versionCode" app/build.gradle | awk -F " " '{print $2}'`
#          versionName=`grep "versionName" app/build.gradle | awk -F ''\"'' '{print $2}'`
#          echo "versionResult=$versionName.$versionCode"  >> $GITHUB_ENV
#
#      # 获取git log
#      - name: Get git log
#        id: git_log
#        run: |
#          updateLog=`git log --pretty=format:"%s" -1`
#          echo "updateLog=$updateLog" >> $GITHUB_ENV
#
#      # 获取发送者
#      - name: Sender
#        run: echo "sender=$GITHUB_ACTOR" >> $GITHUB_ENV

#      # 发送邮件
#      - name: Send mail
#        uses: dawidd6/action-send-mail@v3
#        with:
#          server_address: smtp.gmail.com
#          server_port: 465
#          username: ${{ secrets.MAIL_USERNAME }}
#          password: ${{ secrets.MAIL_PASSWORD }}
#          subject: Github Actions job result
#          to: viperjooy@gmail.com
#          from: viper github action
#          secure: true
#          body: "吃饭! \n触发人：${{ env.sender }} \n版本：${{ env.versionResult }} \n提交内容：${{ env.updateLog }}"